Set oShell = CreateObject("Shell.Application")
oShell.ShellExecute "C:\RClone\.\rclone","mount elz01: E: --network-mode --volname BKTDatArsiv --config=C:/RClone/rclone.conf --cache-dir=C:/WSRCTemp/BKTDatArsiv --cache-workers=4 --vfs-cache-max-age=24h --vfs-cache-mode=full --vfs-read-chunk-size=128K --vfs-read-chunk-size-limit=4M --max-read-ahead=0 --use-mmap --local-no-check-updated --buffer-size=off --no-checksum --no-modtime --checkers=0 --use-cookies --read-only", , "runas", 1
oShell.ShellExecute "C:\RClone\.\rclone","mount elz02: F: --network-mode --volname BKTWatArsiv --config=C:/RClone/rclone.conf --cache-dir=C:/WSRCTemp/BKTWatArsiv --cache-workers=4 --vfs-cache-max-age=24h --vfs-cache-mode=full --vfs-read-chunk-size=128K --vfs-read-chunk-size-limit=4M --max-read-ahead=0 --use-mmap --local-no-check-updated --buffer-size=off --no-checksum --no-modtime --checkers=0 --use-cookies --read-only", , "runas", 1
oShell.ShellExecute "C:\RClone\.\rclone","mount elz03: G: --network-mode --volname BKTRatArsiv --config=C:/RClone/rclone.conf --cache-dir=C:/WSRCTemp/BKTRatArsiv --cache-workers=4 --vfs-cache-max-age=24h --vfs-cache-mode=full --vfs-read-chunk-size=128K --vfs-read-chunk-size-limit=4M --max-read-ahead=0 --use-mmap --local-no-check-updated --buffer-size=off --no-checksum --no-modtime --checkers=0 --use-cookies --read-only", , "runas", 1
oShell.ShellExecute "C:\RClone\.\rclone","mount elz04: H: --network-mode --volname BKTYatArsiv --config=C:/RClone/rclone.conf --cache-dir=C:/WSRCTemp/BKTYatArsiv --cache-workers=4 --vfs-cache-max-age=24h --vfs-cache-mode=full --vfs-read-chunk-size=128K --vfs-read-chunk-size-limit=4M --max-read-ahead=0 --use-mmap --local-no-check-updated --buffer-size=off --no-checksum --no-modtime --checkers=0 --use-cookies --read-only", , "runas", 1
oShell.ShellExecute "C:\RClone\.\rclone","mount elz05: M: --network-mode --volname BKTCatArsiv --config=C:/RClone/rclone.conf --cache-dir=C:/WSRCTemp/BKTCatArsiv --cache-workers=4 --vfs-cache-max-age=24h --vfs-cache-mode=full --vfs-read-chunk-size=128K --vfs-read-chunk-size-limit=4M --max-read-ahead=0 --use-mmap --local-no-check-updated --buffer-size=off --no-checksum --no-modtime --checkers=0 --use-cookies --read-only", , "runas", 1

'ABDEFGHIJKLMNO PQRSTUVWXYZ
'net share BirinciSunucu=C:\Hardisk
'net use M: \\servermaster\BirinciSunucu /persistent:yes
